{
  "uid" : "aa5091ae834b2505",
  "name" : "loginToApplication_Test",
  "fullName" : "Task_10.loginToApplication_Test",
  "historyId" : "39df223a00f9f0173bbcf1f5639e8cfd",
  "time" : {
    "start" : 1632575185679,
    "stop" : 1632575187226,
    "duration" : 1547
  },
  "description" : "Login to app",
  "descriptionHtml" : "<p>Login to app</p>\n",
  "status" : "broken",
  "statusMessage" : "\nMethod Task_10.loginToApplication_Test(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Task_10@4a7761b1] should have thrown an exception of type class java.lang.AssertionError",
  "statusTrace" : "org.testng.TestException: \nMethod Task_10.loginToApplication_Test(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Task_10@4a7761b1] should have thrown an exception of type class java.lang.AssertionError\r\n\tat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)\r\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:28)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:829)\r\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "setUpDriver",
    "time" : {
      "start" : 1632575144355,
      "stop" : 1632575156547,
      "duration" : 12192
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "preconditions",
    "time" : {
      "start" : 1632575156549,
      "stop" : 1632575161110,
      "duration" : 4561
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "description" : "Login to app",
    "status" : "broken",
    "statusMessage" : "\nMethod Task_10.loginToApplication_Test(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Task_10@4a7761b1] should have thrown an exception of type class java.lang.AssertionError",
    "statusTrace" : "org.testng.TestException: \nMethod Task_10.loginToApplication_Test(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Task_10@4a7761b1] should have thrown an exception of type class java.lang.AssertionError\r\n\tat org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)\r\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\r\n\tat org.testng.TestRunner.run(TestRunner.java:596)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:28)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)\r\n\tat org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\r\n\tat java.base/java.lang.Thread.run(Thread.java:829)\r\n",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "73b4eebb695d4d37",
      "name" : "screenshots",
      "source" : "73b4eebb695d4d37.png",
      "type" : "image/png",
      "size" : 54111
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "closeDriver",
    "time" : {
      "start" : 1632575188135,
      "stop" : 1632575191312,
      "duration" : 3177
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "package",
    "value" : "Task_10"
  }, {
    "name" : "testClass",
    "value" : "Task_10"
  }, {
    "name" : "testMethod",
    "value" : "loginToApplication_Test"
  }, {
    "name" : "parentSuite",
    "value" : "Lecture 10"
  }, {
    "name" : "suite",
    "value" : "Login to app"
  }, {
    "name" : "subSuite",
    "value" : "Task_10"
  }, {
    "name" : "host",
    "value" : "DESKTOP-JBSCKF2"
  }, {
    "name" : "thread",
    "value" : "4752@DESKTOP-JBSCKF2.TestNG-tests-1(14)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "arg0",
    "value" : "user"
  }, {
    "name" : "arg1",
    "value" : "sauce"
  }, {
    "name" : "arg2",
    "value" : "Epic sadface: Username and password do not match any user in this service"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "aa5091ae834b2505.json",
  "parameterValues" : [ "user", "sauce", "Epic sadface: Username and password do not match any user in this service" ]
}